# Generated by Django 5.0.6 on 2024-06-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_teacher_price_alter_teacher_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.URLField(db_index=True, default='no', unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.URLField(db_index=True, unique=True),
        ),
    ]
