# Generated by Django 5.0.6 on 2024-06-16 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_teacher_photo_alter_article_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.DeleteModel(
            name='CategoryTeacher',
        ),
    ]
