# Generated by Django 5.0.6 on 2024-06-16 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_teacher_category_delete_categoryteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
